version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./pages/index.html:/usr/share/nginx/html/index.html

  app:
    build: ./app
    volumes:
      - app-logs:/var/log/app
    deploy:
      replicas: 3

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql

volumes:
  app-logs:
  db-data:
  db-logs:
